### PR TITLE
More validation for partial read parameters

### LINKED ISSUE #108: MATLAB crashed while using zarrread function on a S3 bucket
I can consistently reproduce the crash on Windows.

zarrinfo is working fine.

**Repro steps:**
```
>> zarrinfo('https://noaa-nwm-retro-v2-zarr-pds.s3.amazonaws.com/elevation/')

ans = 

  struct with fields:

                chunks: [2×1 double]
            compressor: [1×1 struct]
                 dtype: '<f4'
            fill_value: 'NaN'
               filters: []
                 order: 'C'
                 shape: [2×1 double]
           zarr_format: 2
             node_type: 'array'
    x_ARRAY_DIMENSIONS: {2×1 cell}
           coordinates: 'latitude longitude'
             long_name: 'Feature Elevation'
         standard_name: 'Elevation'
                 units: 'meters'

>> out = zarrread('https://noaa-nwm-retro-v2-zarr-pds.s3.amazonaws.com/elevation/');
% MATLAB crashes

```

### LINKED ISSUE #110: Partial read: Improvement to error messages
Here, I am using the zarr array stored here: https://github.com/mathworks/MATLAB-support-for-Zarr-files/tree/main/test

1. Start parameter is out of bounds
```
>> out = zarrread('grp_v2/arr_v2',Start=[30 40])
Error using ZarrPy>readZarr (line 107)
Python Error: IndexError: Computing interval slice for dimension 0: (29, 19) do not specify a valid closed index
interval [source
locations='tensorstore/index_interval.cc:358\ntensorstore/index_interval.cc:401\ntensorstore/index_space/internal/numpy_indexing_spec.cc:499\ntensorstore/index_space/internal/numpy_indexing_spec.cc:499\ntensorstore/index_space.h:438']

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2. Count parameter is out of bounds
```
>> out = zarrread('grp_v2/arr_v2',Start=[],Count=[30 40])
Error using ZarrPy>readZarr (line 107)
Python Error: ValueError: OUT_OF_RANGE: Propagated bounds [0, 20), with size=20, for dimension 0 are
incompatible with existing bounds [0, 30), with size=30. [transform='Rank 2 -> 2 index space transform:   Input
domain:     0: [0, 30)     1: [0, 40)   Output index maps:     out[0] = 0 + 1 * in[0]     out[1] = 0 + 1 * in[1]
'] [domain='{origin={0, 0}, shape={20, 25}}'] [source
locations='tensorstore/index_space/internal/propagate_bounds.cc:285\ntensorstore/index_space/index_transform.h:991']

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

3. @krisfed For the following case, we have been following to read the whole HDF5 dataset if the input is defined as inf, so would you prefer a similar behavior in case of zarr partial read as well?

_If any element of count is Inf, then h5read reads until the end of the corresponding dimension._([ref](https://www.mathworks.com/help/matlab/ref/h5read.html#mw_81bd7404-41be-4ab6-b990-5addedebf126))

```
>> zarrread('prt_grp/arr_1',Count=[inf inf])
Error using zarrread (line 31)
 zarrread('prt_grp/arr_1',Count=[inf inf])
                                ^^^^^^^^^
Invalid value for 'Count' argument. Value must be integer.
```

### LINKED ISSUE #113: Check behavior when using out-of-bound value for the "stride" parameter
If an out-of-bound value is used for the start and count parameter, then I get a hard error. However, in case of the stride parameter, an empty double is returned. Could you please check the behavior?

```
>> zarrcreate('prt_grp/myarr/',[10 10]);
>> zarrwrite('prt_grp/myarr/',ones([10 10]));
>> zarrread('prt_grp/myarr/',Start=[100 100])
Error using ZarrPy>readZarr (line 107)
Python Error: IndexError: Computing interval slice for dimension 0: (99, 9) do not specify a valid closed index
interval [source
locations='tensorstore/index_interval.cc:358\ntensorstore/index_interval.cc:401\ntensorstore/index_space/internal/numpy_indexing_spec.cc:499\ntensorstore/index_space/internal/numpy_indexing_spec.cc:499\ntensorstore/index_space.h:438']

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 

>> zarrread('prt_grp/myarr/',Stride=[100 100])

ans =

     []

```

### PR DESCRIPTION
**Pull request by krisfed**
Changes include:

1. Preventing a crash when trying to read too much data ( Fixes #108 )

    a. The crash is caused by running out of memory, and the best we can do is error out instead of crashing. There isn't an easy way to determine memory limit in MATLAB, so doing a very hacky workaround of trying to create a zeros array of same size and datatype and seeing if it errors. Luckily creating an array like that is efficient and errors out quickly. At least this is better than accidentally causing the whole MATLAB to crash.

    b. To know the datatype before reading the data I am using the results from `zarrinfo` (instead of introspection on already read data). To determine datatype from `zarrinfo` I needed to add `fromZarrType` method to ZarrDatatype.m

    c. Added a test for this in tZarrRead - `tooBigArray`.

    d. Example of the proposed error when reading data that's too big:
```
>> d = zarrread('https://noaa-nwm-retro-v2-zarr-pds.s3.amazonaws.com/elevation/', Count=[100000,100000])
Error using Zarr/read (line 346)
Reading requested data (100000-by-100000 single array) would exceed maximum array size preference. Select a smaller subset of data to read.

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2. Replacing TensorStore errors (which are a bit hard to interpret) with our own errors for when Start/Stride/Count are out of bounds ( Fixes #110 ). This also makes sure we error out when Stride is too big ( Fixes #113 ). For example (on 3x4 Zarr array):
   
**Start too big**

Before:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Start=[5, 5])
Error using ZarrPy>readZarr (line 107)
Python Error: IndexError: Computing interval slice for dimension 0: (4, 2) do not
specify a valid closed index interval [source
locations='tensorstore/index_interval.cc:360\ntensorstore/index_interval.cc:403\ntensorstore/index_space/internal/numpy_indexing_spec.cc:506\ntensorstore/index_space/internal/numpy_indexing_spec.cc:506\ntensorstore/index_space.h:440']

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

After:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Start=[5, 5])
Error using Zarr.processPartialReadParams (line 107)
Elements in Start must not exceed the corresponding Zarr array dimensions.

Error in Zarr/read (line 317)
            start = Zarr.processPartialReadParams(start, info.shape,...
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
```

**Stride too big**

Before:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Stride=[10, 10])

d =

     []
```

After:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Stride=[10, 10])
Error using Zarr.processPartialReadParams (line 107)
Elements in Stride must not exceed the corresponding Zarr array dimensions.

Error in Zarr/read (line 319)
            stride = Zarr.processPartialReadParams(stride, info.shape,...
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
 
**Combination of Count and Start is too big**

Before:
```
d = zarrread("dataFiles/grp_v2/smallArr", Start=[1,2], Count=[3,4])
Error using ZarrPy>readZarr (line 107)
Python Error: ValueError: OUT_OF_RANGE: Propagated bounds [0, 4), with size=4, for
dimension 1 are incompatible with existing bounds [1, 5), with size=4. [transform='Rank
2 -> 2 index space transform:   Input domain:     0: [0, 3)     1: [1, 5)   Output index
maps:     out[0] = 0 + 1 * in[0]     out[1] = 0 + 1 * in[1] '] [domain='{origin={0, 0},
shape={3, 4}}'] [source
locations='tensorstore/index_space/internal/propagate_bounds.cc:287\ntensorstore/index_space/index_transform.h:994']

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

After:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Start=[1,2], Count=[3,4])
Error using Zarr/read (line 326)
Requested Count in combination with other parameters exceeds Zarr array dimensions.

Error in zarrread (line 36)
data = zarrObj.read(options.Start, options.Count, options.Stride);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```

3. Not allowing logical values for Start/Stride/Count. Previously you could get a following error:
```
>> d = zarrread("dataFiles/grp_v2/smallArr", Start="")
Error using zarrread (line 30)
 d = zarrread("dataFiles/grp_v2/smallArr", Start="")
                                                 ^^
Invalid value for 'Start' argument. Value must be numeric or logical.
```

But logical values do not make sense for Start/Stride/Count, so I added a `mustBeNumeric` validator. Now the behavior is clearer:

```
>> d = zarrread("dataFiles/grp_v2/smallArr", Start="")
Error using zarrread (line 30)
 d = zarrread("dataFiles/grp_v2/smallArr", Start="")
                                                 ^^
Invalid value for 'Start' argument. Value must be numeric.

>> d = zarrread("dataFiles/grp_v2/smallArr", Start=[true, true])
Error using zarrread (line 30)
 d = zarrread("dataFiles/grp_v2/smallArr", Start=[true, true])
                                                 ^^^^^^^^^^^^
Invalid value for 'Start' argument. Value must be numeric.
```

### CODE REVIEW

File: Zarr.m [hunk 1]
```diff
@@ -315,20 +322,38 @@ function makeZarrGroups(existingParentPath, newGroupsPath)
...
             endInds = start + stride.*count;
 
+            % Store the datatype
+            obj.Datatype = ZarrDatatype.fromZarrType(info.dtype);
+
+            % Check if reading requested data might exceed available memory
+            try
+                zeros(count, obj.Datatype.MATLABType);
+            catch ME
+                if strcmp(ME.identifier, 'MATLAB:array:SizeLimitExceeded')
```
Comment (jm9176) [inline Zarr.m:345]: Why did you have to use IF here?

**Review by jm9176 — APPROVED** [review]

File: Zarr.m (hunk 1 above)
Comment (krisfed) [reply Zarr.m:345]: Here I only want to check for the error related to exceeding size limit. I am choosing to silently swallow any other possible errors (rare/unlikely edge-cases). We are trying to create an array of zeros here just as a way to see if reading a similarly-sized array from Zarr file will exceed the memory limit (unfortunately couldn't find a better way) , so my thinking is that any other errors would be unrelated, and we shouldn't throw them and interrupt user workflow. If something goes wrong with creating an array if zeros that is unrelated to memory limit, we should just try reading from the zarr file anyway.

Comment (jm9176) [reply Zarr.m:345]: Thanks for clarifying this.
